"""Shared Sudoku model, grid topology, and technique helper facade.

This package preserves the historical `sudoku_solver.techniques.common`
import path while keeping the implementation split into focused modules.
Public helpers use row-major cell indices from 0 to 80 and candidate bitmasks
where bit 0 represents digit 1 and bit 8 represents digit 9.
"""

from __future__ import annotations

from .bitmask import (
    ALL_DIGITS_MASK,
    DIGIT_VALUES,
    MASK_BIT_COUNTS,
    MASK_DIGITS,
    MASK_INDEXES,
    bit,
    bit_count,
    bits,
    digits_from_mask,
    is_single,
    single_digit,
)
from .grid import (
    ALL_UNITS,
    BOX_OF,
    BOX_UNITS,
    CELL_INDICES,
    CELL_UNIT_INDICES,
    CELL_UNITS,
    COL_OF,
    COL_UNITS,
    COLUMN_INDICES,
    PEERS,
    ROW_INDICES,
    ROW_OF,
    ROW_UNITS,
    cell_text,
    cells_text,
    forced_cell_reason,
    i_to_rc,
    rc_to_i,
    unit_text,
)
from .iter_utils import pair_combinations, sized_combinations, zip_pairs
from .moves import (
    Elimination,
    ExplanationStep,
    Move,
    Placement,
    TechniqueTiming,
    elimination_key,
    elimination_text,
    placement_text,
    source_digit_roles_for_cells,
)
from .queries import (
    UnitCandidateCache,
    bivalue_candidate_cells,
    bivalue_cells_by_mask,
    other_bivalue_digit,
    shared_peer_eliminations,
    shared_peers,
    strong_links_for_digit,
    trivalue_candidate_cells,
    unsolved_cells,
)
from .simulation import (
    apply_move_to_candidates,
    candidate_totals,
    candidates_consistency_ok,
    changed_candidates_consistency_ok,
    eliminate_digit_from_candidates,
    place_digit_in_candidates,
)
from .state import SudokuState
from .technique import Technique
from .types import (
    CellDigit,
    CellGroup,
    CellPair,
    EliminationKey,
    IndexDigit,
    IndexedCellGroup,
    MaskTransition,
    SourceDigitRole,
    SourceDigitRoles,
    UnitCandidateCacheKey,
)

__all__ = [
    "ALL_DIGITS_MASK",
    "ALL_UNITS",
    "BOX_OF",
    "BOX_UNITS",
    "CELL_INDICES",
    "CELL_UNITS",
    "CELL_UNIT_INDICES",
    "COL_OF",
    "COL_UNITS",
    "COLUMN_INDICES",
    "DIGIT_VALUES",
    "MASK_BIT_COUNTS",
    "MASK_DIGITS",
    "MASK_INDEXES",
    "PEERS",
    "ROW_INDICES",
    "ROW_OF",
    "ROW_UNITS",
    "CellDigit",
    "CellGroup",
    "CellPair",
    "Elimination",
    "EliminationKey",
    "ExplanationStep",
    "IndexDigit",
    "IndexedCellGroup",
    "MaskTransition",
    "Move",
    "Placement",
    "SourceDigitRole",
    "SourceDigitRoles",
    "SudokuState",
    "Technique",
    "TechniqueTiming",
    "UnitCandidateCache",
    "UnitCandidateCacheKey",
    "apply_move_to_candidates",
    "bit",
    "bit_count",
    "bits",
    "bivalue_candidate_cells",
    "bivalue_cells_by_mask",
    "candidate_totals",
    "candidates_consistency_ok",
    "cell_text",
    "cells_text",
    "changed_candidates_consistency_ok",
    "digits_from_mask",
    "eliminate_digit_from_candidates",
    "elimination_key",
    "elimination_text",
    "forced_cell_reason",
    "i_to_rc",
    "is_single",
    "other_bivalue_digit",
    "pair_combinations",
    "place_digit_in_candidates",
    "placement_text",
    "rc_to_i",
    "shared_peer_eliminations",
    "shared_peers",
    "single_digit",
    "sized_combinations",
    "source_digit_roles_for_cells",
    "strong_links_for_digit",
    "trivalue_candidate_cells",
    "unit_text",
    "unsolved_cells",
    "zip_pairs",
]
